packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  bcrypt: true
  esbuild: false
  prisma: true
  sharp: true
  unrs-resolver: true
